### ISSUE TITLE
Press and Turn

### ISSUE THREAD

**Issue by biva** [JoryHogeveen/HomeAssistantConfig#2]
Hello, and thank you so much for your blueprint. I'm wondering if you could add the "press+turn" option? It should be available because I find it if I create an automation from scratch. It's called 
```
type:` Press Rotate Knob HUE Mode Only
subtype: right
```
(left works as well)

Thank you again

**Comment by JoryHogeveen** [comment]
Hi @biva 

This repository is just me sharing what I've created for my own needs for free so others can use it as well.
You are very welcome to contribute and create a PR to add such functionality and enhance the overall blueprint :)

Cheers! Jory

**Comment by biva** [comment]
Thanks for your quick feedback. Unfortunately, I'm not skilled in coding, but looking at your code, I'd like to try. Would you be able to guide me so that I can find the right naming/code for this action? I understand it will look like "rotate_right" . Maybe "press_rotate_right". But I don't know where to find this information.
Same for "command == 'remote_button_long_press'" ?

With these info, I guess I can create the additional 2 actions.

Thanks again

**Comment by biva** [comment]
Oh, I realise I wasn't clear about which file I'm referring to: https://github.com/JoryHogeveen/HomeAssistantConfig/blob/c97016bee95cb13a7437087b994665fe609873cf/blueprints/automation/tuya/tuya-TS004F-knob.yaml

**Comment by biva** [comment]
I managed to find out! In fact most of the code was there, I just needed to create the option in it. @JoryHogeveen I didn't know how to create a PR on your repository, so I created it in my repository: please feel free to integrate it in yours!

[blueprints/automation/tuya/tuya-TS004F-knob.yaml](https://github.com/biva/homeassistant/blob/main/tuya-TS004F-qja6nq5z-knob)

**Comment by biva** [comment]
(and I changed the manufacturer to fit with mine)

**Comment by JoryHogeveen** [comment]
Hi @biva 

Good job! Since yours is apparently a different device then mine, a PR with these changes isn't applicable since it would overwrite my device :) A separate blueprint for this purpose would be the best solution which you've just created.
I'm closing this topic since you've solved it 👍 

Cheers! Jory

**Comment by JoryHogeveen** [comment]
Oh, just for info!
In case you'd like to work on more blueprints etc. there is a tool you can very easily use to "listen" to Zigbee events and see the code your devices send when triggered.
You can install it through HACS: https://github.com/mdeweerd/zha-toolkit
It's really an awesome tool to get more insights into your Zigbee network.

**Comment by biva** [comment]
Thanks a lot!
